// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCViuT-vEo8Ta35vGcMvxgoiEkJmCv5QVk',
    appId: '1:885105287120:web:48f819cd4de9672ad1a3d5',
    messagingSenderId: '885105287120',
    projectId: 'clinic-connect-83159',
    authDomain: 'clinic-connect-83159.firebaseapp.com',
    storageBucket: 'clinic-connect-83159.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfmekq9zbZEcQkghgdBcXa-i4WJ3sFvSA',
    appId: '1:885105287120:android:184a5ca540d6f1ecd1a3d5',
    messagingSenderId: '885105287120',
    projectId: 'clinic-connect-83159',
    storageBucket: 'clinic-connect-83159.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTwq9ZlcYnCCLSj7GNA5I5EJeV0PZ_oCI',
    appId: '1:885105287120:ios:7481eadf19b16b4dd1a3d5',
    messagingSenderId: '885105287120',
    projectId: 'clinic-connect-83159',
    storageBucket: 'clinic-connect-83159.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTwq9ZlcYnCCLSj7GNA5I5EJeV0PZ_oCI',
    appId: '1:885105287120:ios:7481eadf19b16b4dd1a3d5',
    messagingSenderId: '885105287120',
    projectId: 'clinic-connect-83159',
    storageBucket: 'clinic-connect-83159.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );
}
